name: BuffStreams Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          sudo playwright install-deps
            libgtk-4-1 libgraphene-1.0-0 libvpx9 libevent-2.1-7 libopus0 \
            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav gstreamer1.0-gl \
            libflite1 libavif16 libharfbuzz-icu0 libsecret-1-0 libhyphen0 \
            libgles2-mesa-dev libx264-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      - name: Run BuffStreams playlist script
        run: python update_buff.py

      - name: Upload playlists as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buffstreams-playlists
          path: |
            BuffStreams_VLC.m3u8
            BuffStreams_TiviMate.m3u8
